<?php

namespace DoctrineProxies\__CG__\TakeOutHotline\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Customer extends \TakeOutHotline\Entities\Customer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'id', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'firstName', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'lastName', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'address', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'address2', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'phone', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'city', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'postalCode', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'remarks', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'status', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'email', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'mypass', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'nameTitle', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'emailVerified', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'orders'];
        }

        return ['__isInitialized__', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'id', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'firstName', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'lastName', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'address', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'address2', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'phone', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'city', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'postalCode', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'remarks', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'status', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'email', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'mypass', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'nameTitle', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'emailVerified', '' . "\0" . 'TakeOutHotline\\Entities\\Customer' . "\0" . 'orders'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Customer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', []);

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', [$firstName]);

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', []);

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', [$lastName]);

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress2', []);

        return parent::getAddress2();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress2($address2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress2', [$address2]);

        return parent::setAddress2($address2);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalCode', []);

        return parent::getPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostalCode($postalCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostalCode', [$postalCode]);

        return parent::setPostalCode($postalCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemarks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemarks', []);

        return parent::getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemarks($remarks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemarks', [$remarks]);

        return parent::setRemarks($remarks);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getMypass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMypass', []);

        return parent::getMypass();
    }

    /**
     * {@inheritDoc}
     */
    public function setMypass($mypass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMypass', [$mypass]);

        return parent::setMypass($mypass);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameTitle', []);

        return parent::getNameTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameTitle($nameTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameTitle', [$nameTitle]);

        return parent::setNameTitle($nameTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailVerified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailVerified', []);

        return parent::getEmailVerified();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailVerified($emailVerified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailVerified', [$emailVerified]);

        return parent::setEmailVerified($emailVerified);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrders', []);

        return parent::getOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrders($orders)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrders', [$orders]);

        return parent::setOrders($orders);
    }

}
