<?php

namespace DoctrineProxies\__CG__\TakeOutHotline\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Category extends \TakeOutHotline\Entities\Category implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TakeOutHotline\\Entities\\Category' . "\0" . 'id', '' . "\0" . 'TakeOutHotline\\Entities\\Category' . "\0" . 'catName', '' . "\0" . 'TakeOutHotline\\Entities\\Category' . "\0" . 'catDescription', '' . "\0" . 'TakeOutHotline\\Entities\\Category' . "\0" . 'client', '' . "\0" . 'TakeOutHotline\\Entities\\Category' . "\0" . 'isDeleted', '' . "\0" . 'TakeOutHotline\\Entities\\Category' . "\0" . 'updatedLast', '' . "\0" . 'TakeOutHotline\\Entities\\Category' . "\0" . 'menu_addon', '' . "\0" . 'TakeOutHotline\\Entities\\Category' . "\0" . 'menus'];
        }

        return ['__isInitialized__', '' . "\0" . 'TakeOutHotline\\Entities\\Category' . "\0" . 'id', '' . "\0" . 'TakeOutHotline\\Entities\\Category' . "\0" . 'catName', '' . "\0" . 'TakeOutHotline\\Entities\\Category' . "\0" . 'catDescription', '' . "\0" . 'TakeOutHotline\\Entities\\Category' . "\0" . 'client', '' . "\0" . 'TakeOutHotline\\Entities\\Category' . "\0" . 'isDeleted', '' . "\0" . 'TakeOutHotline\\Entities\\Category' . "\0" . 'updatedLast', '' . "\0" . 'TakeOutHotline\\Entities\\Category' . "\0" . 'menu_addon', '' . "\0" . 'TakeOutHotline\\Entities\\Category' . "\0" . 'menus'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Category $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMenus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenus', []);

        return parent::getMenus();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenus($menus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenus', [$menus]);

        return parent::setMenus($menus);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCatName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCatName', []);

        return parent::getCatName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCatName($catName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCatName', [$catName]);

        return parent::setCatName($catName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCatDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCatDescription', []);

        return parent::getCatDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setCatDescription($catDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCatDescription', [$catDescription]);

        return parent::setCatDescription($catDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', []);

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient($client)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', [$client]);

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDeleted', []);

        return parent::getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDeleted($isDeleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDeleted', [$isDeleted]);

        return parent::setIsDeleted($isDeleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedLast()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedLast', []);

        return parent::getUpdatedLast();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedLast($updatedLast)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedLast', [$updatedLast]);

        return parent::setUpdatedLast($updatedLast);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuAddon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuAddon', []);

        return parent::getMenuAddon();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenuAddon($menu_addon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenuAddon', [$menu_addon]);

        return parent::setMenuAddon($menu_addon);
    }

}
