<?php

namespace DoctrineProxies\__CG__\TakeOutHotline\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Menus extends \TakeOutHotline\Entities\Menus implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'id', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'menu_name', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'price_type', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'menu_category', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'menu_description', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'menu_image', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'is_deleted', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'updated_last', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'updated_by', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'order_item', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'menu_addon', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'menuPrices', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'category'];
        }

        return ['__isInitialized__', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'id', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'menu_name', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'price_type', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'menu_category', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'menu_description', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'menu_image', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'is_deleted', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'updated_last', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'updated_by', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'order_item', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'menu_addon', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'menuPrices', '' . "\0" . 'TakeOutHotline\\Entities\\Menus' . "\0" . 'category'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Menus $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory($category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuPrices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuPrices', []);

        return parent::getMenuPrices();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenuPrices($menuPrices)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenuPrices', [$menuPrices]);

        return parent::setMenuPrices($menuPrices);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuName', []);

        return parent::getMenuName();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenuName($menu_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenuName', [$menu_name]);

        return parent::setMenuName($menu_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceType', []);

        return parent::getPriceType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceType($price_type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceType', [$price_type]);

        return parent::setPriceType($price_type);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuCategory', []);

        return parent::getMenuCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenuCategory($menu_category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenuCategory', [$menu_category]);

        return parent::setMenuCategory($menu_category);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuDescription', []);

        return parent::getMenuDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenuDescription($menu_description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenuDescription', [$menu_description]);

        return parent::setMenuDescription($menu_description);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuImage', []);

        return parent::getMenuImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenuImage($menu_image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenuImage', [$menu_image]);

        return parent::setMenuImage($menu_image);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDeleted', []);

        return parent::getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDeleted($is_deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDeleted', [$is_deleted]);

        return parent::setIsDeleted($is_deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedLast()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedLast', []);

        return parent::getUpdatedLast();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedLast($updated_last)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedLast', [$updated_last]);

        return parent::setUpdatedLast($updated_last);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy($updated_by)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$updated_by]);

        return parent::setUpdatedBy($updated_by);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderItem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderItem', []);

        return parent::getOrderItem();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderItem($order_item)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderItem', [$order_item]);

        return parent::setOrderItem($order_item);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuAddon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuAddon', []);

        return parent::getMenuAddon();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenuAddon($menu_addon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenuAddon', [$menu_addon]);

        return parent::setMenuAddon($menu_addon);
    }

}
